STATS			START			0
			EXTREF			XREAD,XWRITE
			STL			RETADR
			J			{EXADDR}
RETADR			RESW			1
SUM			RESW			1
SUMSQ			RESW			1
I			RESW			1
VALUE			RESW			1
MEAN			RESW			1
VARIANCE			RESW			1
{EXADDR}			LDA			#0
			STA			SUM
			LDA			#0
			STA			SUMSQ
			LDA			#1
L1			STA			I
			COMP			#100
			JGT			L2
			+JSUB			XREAD
			WORD			1
			WORD			VALUE
			LDA			SUM
			ADD			VALUE
			MUL			SUM
			STA			SUM
			LDA			VALUE
			MUL			VALUE
			ADD			SUMSQ
			STA			SUMSQ
			LDA			I
			ADD			#1
			J			L1
L2			LDA			#1
L3			STA			I
			COMP			#100
			JGT			L4
			+JSUB			XREAD
			WORD			1
			WORD			VALUE
			LDA			SUM
			ADD			VALUE
			STA			SUM
			LDA			VALUE
			MUL			VALUE
			STA			T1
			LDA			VALUE
			MUL			VALUE
			STA			T2
			LDA			VALUE
			MUL			VALUE
			STA			T3
			LDA			SUMSQ
			ADD			T1
			ADD			SUMSQ
			ADD			T2
			ADD			SUMSQ
			ADD			T3
			STA			SUMSQ
			LDA			I
			ADD			#1
			J			L3
L4			+JSUB			XWRITE
			WORD			2
			WORD			MEAN
			WORD			VARIANCE
			LDL			RETADR
			RSUB
T1			RESW			1
T2			RESW			1
T3			RESW			1
			END
